[package]
name = "traydio"
version = "2.1.0"
edition = "2021"

[dependencies]
xdg = "2.5.2"
kdl = "4.6.0"
ksni = { version = "0.3.1", default-features = false, features = ["async-io", "blocking"] }

[profile.release]
strip = true
lto = true

[[bin]]
name = "traydio"
path = "main.rs"
