[package]
name = "traydio"
version = "3.0.0"
edition = "2024"

[dependencies]
xdg = "3.0.0"
kdl = "4.6.0"
ksni = "0.3.1"
tokio = "1.47.1"

[profile.release]
strip = true
lto = true

[[bin]]
name = "traydio"
path = "main.rs"
